import type { Metadata } from 'next';
import { Be_Vietnam_Pro } from 'next/font/google';
import '@/styles/globals.css';

const beVietnamPro = Be_Vietnam_Pro({
  weight: ['300', '500', '600'],
  subsets: ['latin'],
  fallback: ['system-ui'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={beVietnamPro.className}>{children}</body>
    </html>
  );
}
